// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/greystone-settings/Current.tsx": () => import("../components/mockups/greystone-settings/Current.tsx"),
  "./components/mockups/greystone-settings/TechnicalClean.tsx": () => import("../components/mockups/greystone-settings/TechnicalClean.tsx")
};
