import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Card, Loading, Metric, Pill } from '../ui';
import { ACCOUNTING_CHART, api, post, qs, type AccountingPeriod, type AccountingSyncResult, type BalanceSheetReport, type CashFlowReport, type EligibleReconciliationLine, type EligibleReconciliationLines, type Journal, type JournalsResponse, type PeriodCloseResult, type PeriodsResponse, type ProfitLossReport, type Reconciliation, type ReconciliationsResponse, type RepPayablesReport, type TrialBalanceReport } from '../../lib/api';
import { day, money } from '../../lib/format';
import { useSession } from '../../lib/session';

const today = () => new Date().toISOString().slice(0, 10);
const dateFields = (from: string, to: string) => qs({ from: from || undefined, to: to || undefined });
function Dates({ from, to, setFrom, setTo }: { from: string; to: string; setFrom: (v: string) => void; setTo: (v: string) => void }) {
  return <div className="toolbar"><label className="field"><span className="label">From</span><input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label className="field"><span className="label">To</span><input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></div>;
}
function Balance({ ok }: { ok: boolean }) { return <Pill tone={ok ? 'teal' : 'red'}>{ok ? 'Balanced' : 'Out of balance'}</Pill>; }

export function AccountingOverview({ onJournal }: { onJournal: (source?: string) => void }) {
  const qc = useQueryClient(); const { notify } = useSession(); const [busy, setBusy] = useState(false); const [lastSync, setLastSync] = useState<AccountingSyncResult | null>(null);
  const periods = useQuery({ queryKey: ['books-periods'], queryFn: () => api<PeriodsResponse>('/api/admin/books/periods') });
  const tb = useQuery({ queryKey: ['books-report-tb-overview'], queryFn: () => api<TrialBalanceReport>('/api/admin/books/reports/trial-balance') });
  async function sync() { setBusy(true); try { const r = await post<AccountingSyncResult>('/api/admin/books/sync', {}); setLastSync(r); notify(`${r.inserted} journal entr${r.inserted === 1 ? 'y' : 'ies'} posted`); await qc.invalidateQueries({ queryKey: ['books'] }); } catch (e) { notify(e instanceof Error ? e.message : 'Sync failed'); } finally { setBusy(false); } }
  const open = periods.data?.periods.filter(p => p.status === 'open').length ?? 0;
  return <><div className="books-hero"><div><div className="label">Unified accounting / control room</div><h2>Books that tie to the source.</h2><p>Project operational commits into an immutable journal, then close the month with evidence.</p></div><button className="btn primary big" onClick={() => void sync()} disabled={busy}>{busy ? 'Syncing…' : 'Sync & backfill'}</button></div>
    {lastSync && (lastSync.pendingProjection || lastSync.unresolved.length) ? <div className="banner books-blocker"><span><b>Posting blocked: {lastSync.unresolved.length} unresolved source change{lastSync.unresolved.length === 1 ? '' : 's'}.</b> {lastSync.unresolved.map(x => `${x.logicalSourceKey}: ${x.reason}`).join(' · ')}</span></div> : null}
    <div className="grid-auto-180"><Metric label="Journal balance" value={tb.data ? money(tb.data.totals.debit) : '—'} sub={tb.data ? `${tb.data.rows.length} active accounts` : 'Loading'} /><Metric label="Open periods" value={String(open)} sub="posting remains available" tone={open ? 'warn' : undefined} /><Metric label="Posting integrity" value={tb.data ? (tb.data.balanced ? 'Balanced' : 'Out of balance') : '—'} sub="debits equal credits" tone={tb.data && !tb.data.balanced ? 'neg' : undefined} /></div>
    <div className="two"><Card title="Operating notes">{lastSync?.assumedCollectionDates ? <div className="note neg"><b>{lastSync.assumedCollectionDates} assumed collection date{lastSync.assumedCollectionDates === 1 ? '' : 's'}</b><br />These postings follow deterministic lender schedule dates, not confirmed receipts. Review source metadata before closing.</div> : <div className="note">Every posted journal is immutable. Source keys and line IDs are retained for reconciliation and audit drilldown.</div>}{lastSync && (lastSync.corrected || lastSync.removed) ? <div className="note" style={{ marginTop: 10 }}><b>{lastSync.corrected} corrected · {lastSync.removed} removed</b><br />Changes post as reversal and replacement journals; original records remain immutable.</div> : null}<button className="linkish" style={{ marginTop: 12 }} onClick={() => onJournal()}>Review the journal →</button></Card><Card title="Period posture" extra="close before export"><div className="pl">{periods.data?.periods.slice(-5).reverse().map(p => <div className="row" key={p.id}><span><b>{day(p.start)} — {day(p.end)}</b><span className="subtle"> · {p.status === 'closed' ? `closed ${p.closedAt ? day(p.closedAt) : ''}` : 'open for posting'}</span></span><Pill tone={p.status === 'closed' ? 'grey' : 'amber'}>{p.status}</Pill></div>)}</div></Card></div></>;
}

export function Journal({ initialSource, onDeal }: { initialSource?: string; onDeal: (id: string) => void }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [accountCode, setAccount] = useState(''); const [sourceKey, setSource] = useState(initialSource ?? '');
  const q = useQuery({ queryKey: ['books-journals', from, to, accountCode, sourceKey], queryFn: () => api<JournalsResponse>(`/api/admin/books/journals${qs({ ...Object.fromEntries(new URLSearchParams(dateFields(from, to))), accountCode: accountCode || undefined, sourceKey: sourceKey || undefined })}`) });
  const journals = q.data?.journals ?? [];
  return <><div className="toolbar"><Dates {...{ from, to, setFrom, setTo }} /><select className="filter" value={accountCode} onChange={e => setAccount(e.target.value)}><option value="">All accounts</option>{ACCOUNTING_CHART.map(a => <option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select><input className="search" placeholder="Source key" value={sourceKey} onChange={e => setSource(e.target.value)} /><span className="count">{journals.length} journals</span></div><Card title="Immutable journal" extra="line-level posting detail"><div className="scroller"><div className="table" style={{ ['--cols' as string]: '105px 180px minmax(260px,1fr) 105px 105px', minWidth: 880 }}><div className="tr th"><div className="td">Date</div><div className="td">Source / lineage</div><div className="td">Account / memo</div><div className="td r">Debit</div><div className="td r">Credit</div></div>{journals.flatMap(j => j.lines.map(l => <div className="tr click" key={`${j.id}-${l.id}`} onClick={() => l.dealId && onDeal(l.dealId)}><div className="td num">{day(j.date)}</div><div className="td"><b>{j.sourceType}</b><span className="subtle mono">{j.sourceKey}</span>{j.correctionDate ? <span className="warn">Correction {day(j.correctionDate)} · logical {j.logicalSourceKey} · v{j.sourceVersion}{j.reversalOf ? ' · reversal' : ' · replacement'}</span> : null}</div><div className="td"><b>{l.accountCode} · {ACCOUNTING_CHART.find(a => a.code === l.accountCode)?.name}</b><span className="subtle">{l.memo || j.memo}{l.dealId ? ` · deal ${l.dealId}` : ''}</span></div><div className="td r num">{l.debit ? money(l.debit) : '—'}</div><div className="td r num">{l.credit ? money(l.credit) : '—'}</div></div>))}{!q.isLoading && !journals.length && <div className="empty">No journal lines match these filters.</div>}</div></div></Card></>;
}

export function Periods() {
  const qc = useQueryClient(); const { notify } = useSession(); const q = useQuery({ queryKey: ['books-periods'], queryFn: () => api<PeriodsResponse>('/api/admin/books/periods') }); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [busy, setBusy] = useState(false);
  async function mutate(p: AccountingPeriod, action: 'close' | 'reopen') { if (!window.confirm(`${action === 'close' ? 'Close' : 'Reopen'} ${day(p.start)} — ${day(p.end)}?`)) return; try { const result = await post<PeriodCloseResult | { ok: true }>(`/api/admin/books/periods/${p.id}/${action}`, {}); notify(action === 'close' && 'checklist' in result ? `Period closed · ${result.checklist.journalCount} journals verified` : `Period ${action}d`); await qc.invalidateQueries({ queryKey: ['books-periods'] }); } catch (e) { notify(e instanceof Error ? e.message : 'Could not update period'); } }
  async function create() { setBusy(true); try { await post('/api/admin/books/periods', { start, end }); setStart(''); setEnd(''); notify('Accounting period created'); await qc.invalidateQueries({ queryKey: ['books-periods'] }); } catch (e) { notify(e instanceof Error ? e.message : 'Could not create period'); } finally { setBusy(false); } }
  return <><Card title="Create period" extra="closed periods reject new journal posts"><div className="toolbar"><label className="field"><span className="label">Start</span><input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label className="field"><span className="label">End</span><input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label><button className="btn primary" disabled={!start || !end || busy} onClick={() => void create()}>Create period</button></div></Card><Card title="Accounting periods"><div className="pl">{q.data?.periods.map(p => <div className={`row period-row ${p.status === 'closed' ? 'closed' : ''}`} key={p.id}><span><b>{day(p.start)} — {day(p.end)}</b><span className="subtle"> · {p.status === 'closed' ? `Closed ${p.closedAt ? day(p.closedAt) : ''}` : 'Open'}</span></span><Pill tone={p.status === 'closed' ? 'grey' : 'amber'}>{p.status}</Pill><button className="btn" onClick={() => void mutate(p, p.status === 'closed' ? 'reopen' : 'close')}>{p.status === 'closed' ? 'Reopen' : 'Close period'}</button></div>)}</div></Card></>;
}

export function Reconciliations() {
  const qc = useQueryClient(); const { notify } = useSession(); const q = useQuery({ queryKey: ['books-reconciliations'], queryFn: () => api<ReconciliationsResponse>('/api/admin/books/reconciliations') }); const [selected, setSelected] = useState<Reconciliation | null>(null); const [accountCode, setAccount] = useState('1000'); const [statementStart, setStart] = useState(today()); const [statementDate, setDate] = useState(today()); const [openingBalance, setOpening] = useState('0'); const [statementBalance, setBalance] = useState(''); const [note, setNote] = useState('');
  async function create() { try { await post('/api/admin/books/reconciliations', { accountCode, statementStart, statementDate, openingBalance: Number(openingBalance), statementBalance: Number(statementBalance), note }); setBalance(''); setNote(''); notify('Reconciliation created'); await qc.invalidateQueries({ queryKey: ['books-reconciliations'] }); } catch (e) { notify(e instanceof Error ? e.message : 'Could not create reconciliation'); } }
  return <><Card title="New reconciliation" extra="balances are in dollars"><div className="toolbar"><select className="filter" value={accountCode} onChange={e => setAccount(e.target.value)}>{ACCOUNTING_CHART.filter(a => a.type === 'asset').map(a => <option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select><label className="field"><span className="label">Statement start</span><input type="date" value={statementStart} onChange={e => setStart(e.target.value)} /></label><label className="field"><span className="label">Statement end</span><input type="date" value={statementDate} onChange={e => setDate(e.target.value)} /></label><input className="search" placeholder="Opening balance" inputMode="decimal" value={openingBalance} onChange={e => setOpening(e.target.value)} /><input className="search" placeholder="Statement balance" inputMode="decimal" value={statementBalance} onChange={e => setBalance(e.target.value)} /><input className="search" placeholder="Note (optional)" value={note} onChange={e => setNote(e.target.value)} /><button className="btn primary" disabled={!statementBalance || !statementStart} onClick={() => void create()}>Start reconciliation</button></div></Card><Card title="Reconciliations"><div className="pl">{q.data?.reconciliations.map(r => <button className={`row click recon-row ${r.status === 'completed' ? 'complete' : ''}`} key={r.id} onClick={() => setSelected(r)}><span><b>{r.accountCode} · {day(r.statementDate)}</b><span className="subtle"> · {r.matches.length} matched lines</span></span><span className="num">{money(r.difference)}</span><Pill tone={r.status === 'completed' ? 'teal' : 'amber'}>{r.status}</Pill></button>)}{!q.data?.reconciliations.length && <div className="empty">No reconciliations yet.</div>}</div></Card>{selected && <ReconciliationDetail value={selected} onClose={() => setSelected(null)} />}</>;
}
function ReconciliationDetail({ value, onClose }: { value: Reconciliation; onClose: () => void }) {
  const qc = useQueryClient(); const { notify } = useSession(); const [selected, setSelected] = useState<EligibleReconciliationLine | null>(null); const [error, setError] = useState('');
  const detail = useQuery({ queryKey: ['books-reconciliation', value.id], queryFn: () => api<Reconciliation>(`/api/admin/books/reconciliations/${value.id}`) });
  const eligible = useQuery({ queryKey: ['books-reconciliation-eligible', value.id], queryFn: () => api<EligibleReconciliationLines>(`/api/admin/books/reconciliations/${value.id}/eligible-lines`) });
  const r = detail.data ?? value;
  async function match() { if (!selected) return; setError(''); try { await post<Reconciliation>(`/api/admin/books/reconciliations/${r.id}/matches`, { journalLineId: selected.id, amount: selected.amount }); notify('Journal line matched'); setSelected(null); await Promise.all([qc.invalidateQueries({ queryKey: ['books-reconciliation', r.id] }), qc.invalidateQueries({ queryKey: ['books-reconciliation-eligible', r.id] }), qc.invalidateQueries({ queryKey: ['books-reconciliations'] })]); } catch (e) { const message = e instanceof Error ? e.message : 'Could not match line'; setError(message); notify(message); } }
  async function complete() { if (r.difference !== 0) return; try { await post(`/api/admin/books/reconciliations/${r.id}`, { status: 'completed' }, 'PATCH'); notify('Reconciliation completed'); await qc.invalidateQueries({ queryKey: ['books-reconciliations'] }); await qc.invalidateQueries({ queryKey: ['books-reconciliation', r.id] }); } catch (e) { const message = e instanceof Error ? e.message : 'Could not complete reconciliation'; setError(message); notify(message); } }
  return <div className="scrim" onClick={onClose}><aside className="drawer books-detail" onClick={e => e.stopPropagation()}><button className="btn close" onClick={onClose}>Close</button><div><div className="label">Reconciliation detail</div><h2>{r.accountCode} · {day(r.statementDate)}</h2><p className="muted">Eligible from {day(eligible.data?.statementStart ?? r.statementStart)} through {day(eligible.data?.statementDate ?? r.statementDate)}. Lines claimed by another reconciliation are unavailable.</p></div><div className="grid-auto-180"><Metric label="Opening balance" value={money(r.openingBalance)} /><Metric label="Statement activity" value={money(r.clearedAmount)} /><Metric label="Expected balance" value={money(r.expectedBalance)} /><Metric label="Statement balance" value={money(r.statementBalance)} /><Metric label="Difference" value={money(r.difference)} tone={r.difference ? 'warn' : 'pos'} /></div><Card title="Eligible journal lines" extra={`${eligible.data?.lines.length ?? 0} available`}><div className="pl">{eligible.isError ? <div className="note neg">Could not load eligible lines. {eligible.error instanceof Error ? eligible.error.message : 'Retry from the reconciliation list.'}</div> : eligible.data?.lines.map(line => <button key={line.id} className={`row click eligible-line ${selected?.id === line.id ? 'selected' : ''}`} onClick={() => setSelected(line)} disabled={r.status !== 'open'}><span><b>{day(line.date)} · {line.sourceKey}</b><span className="subtle">{line.label}</span><span className="subtle mono">remaining {money(line.amount)}</span></span><span className="num">{money(line.amount)}</span></button>)}{!eligible.isLoading && !eligible.data?.lines.length && <div className="empty">No eligible lines remain in this statement interval.</div>}</div><div className="toolbar" style={{ marginTop: 12 }}><span className="subtle">{selected ? `${day(selected.date)} · ${selected.sourceKey} selected at ${money(selected.amount)}` : 'Select a line to match its permitted signed amount.'}</span><button className="btn primary" disabled={!selected || r.status !== 'open'} onClick={() => void match()}>Match selected line</button></div>{error && <div className="note neg" style={{ marginTop: 10 }}>{error}</div>}</Card><Card title="Matched lines"><div className="pl">{r.matches.map(m => <div className="row" key={m.journalLineId}><span className="mono">{m.journalLineId}</span><span className="num">{money(m.amount)}</span></div>)}{!r.matches.length && <div className="empty">Nothing matched yet.</div>}</div><div className="toolbar" style={{ marginTop: 12 }}><span className={r.difference === 0 ? 'pos' : 'warn'}>{r.difference === 0 ? 'Difference is zero. This reconciliation can be completed.' : 'Complete becomes available only when the difference is zero.'}</span><button className="btn primary" disabled={r.status !== 'open' || r.difference !== 0} onClick={() => void complete()}>Complete reconciliation</button></div></Card></aside></div>;
}

export function Reports({ onJournal }: { onJournal: (source?: string) => void }) {
  const [report, setReport] = useState<'tb' | 'pl' | 'bs' | 'cf' | 'rep'>('tb'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [asOf, setAsOf] = useState(today()); const range = dateFields(from, to);
  const path = report === 'tb' ? 'trial-balance' : report === 'pl' ? 'profit-loss' : report === 'bs' ? 'balance-sheet' : report === 'cf' ? 'cash-flow' : 'rep-payables';
  const q = useQuery({ queryKey: ['books-report', report, from, to, asOf], queryFn: () => api<TrialBalanceReport | ProfitLossReport | BalanceSheetReport | CashFlowReport | RepPayablesReport>(`/api/admin/books/reports/${path}${report === 'bs' || report === 'rep' ? qs({ asOf }) : range}`) });
  const data = q.data;
  return <><div className="seg pagetabs">{[['tb','Trial balance'],['pl','Profit & loss'],['bs','Balance sheet'],['cf','Direct cash flow'],['rep','Rep payables']].map(([k,l]) => <button className={report === k ? 'on' : ''} key={k} onClick={() => setReport(k as typeof report)}>{l}</button>)}</div><Card title={report === 'bs' || report === 'rep' ? 'As of date' : 'Reporting range'}><Dates {...{ from, to, setFrom, setTo }} />{(report === 'bs' || report === 'rep') && <label className="field"><span className="label">As of</span><input type="date" value={asOf} onChange={e => setAsOf(e.target.value)} /></label>}</Card><ReportBody report={report} data={data} onJournal={onJournal} /></>;
}
function ReportBody({ report, data, onJournal }: { report: string; data: unknown; onJournal: (source?: string) => void }) {
  if (!data) return <Loading error={null} />; const d = data as any; const balanced = 'balanced' in d ? d.balanced : true;
  if (report === 'tb') return <Card title="Trial balance" extra={<Balance ok={balanced} />}><ReportRows rows={d.rows} onJournal={onJournal} totals={d.totals} /></Card>;
  if (report === 'pl') return <><div className="grid-auto-180"><Metric label="Revenue" value={money(d.revenue)} /><Metric label="Net revenue" value={money(d.netRevenue)} /><Metric label="Expenses" value={money(d.expenses)} /><Metric label="Net income" value={money(d.netIncome)} tone={d.netIncome >= 0 ? 'pos' : 'neg'} /></div><Card title="P&L drilldown"><ReportRows rows={d.drilldown} onJournal={onJournal} /></Card></>;
  if (report === 'bs') return <><div className="grid-auto-180"><Metric label="Assets" value={money(d.assets)} /><Metric label="Liabilities" value={money(d.liabilities)} /><Metric label="Equity" value={money(d.equity)} /><Metric label="Status" value={d.balanced ? 'Balanced' : 'Out of balance'} tone={d.balanced ? 'pos' : 'neg'} /></div><Card title="Balance sheet drilldown"><ReportRows rows={d.drilldown} onJournal={onJournal} /></Card></>;
  if (report === 'cf') return <><div className="grid-auto-180"><Metric label="Inflows" value={money(d.inflows)} /><Metric label="Outflows" value={money(d.outflows)} /><Metric label="Net cash" value={money(d.netCash)} tone={d.netCash >= 0 ? 'pos' : 'neg'} /></div><Card title="Cash entries"><div className="pl">{d.entries.map((x: any) => <button className="row click" key={`${x.sourceKey}-${x.date}`} onClick={() => onJournal(x.sourceKey)}><span><b>{day(x.date)}</b><span className="subtle mono"> · {x.sourceKey}</span></span><span className="num">{money(x.amount)}</span></button>)}</div></Card></>;
  return <Card title="Rep payables" extra={<Metric label="Payable" value={money(d.payable)} />}><div className="pl">{d.rows.map((x: any) => <button className="row click" key={`${x.journalId}-${x.sourceKey}`} onClick={() => onJournal(x.sourceKey)}><span><b>{day(x.date)} · {x.repId || 'Unassigned rep'}</b><span className="subtle mono"> · {x.sourceKey}</span></span><span className="num">{money(x.endingEffect)}</span></button>)}</div></Card>;
}
function ReportRows({ rows, onJournal, totals }: { rows: any[]; onJournal: (source?: string) => void; totals?: any }) { return <div className="scroller"><div className="table" style={{ ['--cols' as string]: '85px minmax(220px,1fr) 120px 120px 120px', minWidth: 680 }}><div className="tr th"><div className="td">Code</div><div className="td">Account</div><div className="td r">Debit</div><div className="td r">Credit</div><div className="td r">Balance</div></div>{rows.map(r => <button className="tr click" key={r.accountCode} onClick={() => onJournal(r.journals?.[0])}><div className="td mono">{r.accountCode}</div><div className="td">{r.name}</div><div className="td r num">{money(r.debit || 0)}</div><div className="td r num">{money(r.credit || 0)}</div><div className="td r num">{money(r.balance || 0)}</div></button>)}{totals && <div className="tr total"><div className="td">Total</div><div className="td" /><div className="td r num">{money(totals.debit)}</div><div className="td r num">{money(totals.credit)}</div><div className="td" /></div>}</div></div>; }