import { useState, type ReactNode } from 'react';

const settingsTabs = ['Portal', 'Lenders', 'Referral partners', 'Product rules', 'Teams', 'Reps', 'CRM & thresholds', 'Playbooks', 'Import from sheet', 'Lender remittance'];
const nav = ['Funding overview', 'Master deals', 'Merchants', 'Run payroll', 'Renewals', 'Books', 'Rep roster', 'Settings', 'Audit log'];

const css = `
.cc-settings{--ink:#17323a;--navy:#102e38;--navy-2:#17434d;--teal:#08788a;--teal-deep:#065d6e;--mint:#c7e7b1;--paper:#edf3f2;--surface:#fbfdfc;--line:#cbdad9;--line-soft:#e3ecea;--muted:#668087;--quiet:#8da1a3;min-height:100vh;background:var(--paper);color:var(--ink);font:13px/1.4 'DM Sans',ui-sans-serif,system-ui,sans-serif;letter-spacing:-.01em;-webkit-font-smoothing:antialiased}
.cc-settings *{box-sizing:border-box}.cc-settings button,.cc-settings input,.cc-settings select,.cc-settings textarea{font:inherit}.cc-shell{display:grid;grid-template-columns:226px minmax(0,1fr);min-height:100vh}
.cc-sidebar{background:var(--navy);color:#dbe8e7;padding:19px 12px 15px;display:flex;flex-direction:column;min-height:100vh}.cc-brand{display:flex;gap:10px;align-items:center;padding:2px 10px 18px;border-bottom:1px solid #2a4b52;margin-bottom:18px}.cc-mark{height:29px;width:29px;display:grid;place-items:center;border:1px solid #83b8bc;border-radius:7px;color:#d9f5ed;font:700 16px Georgia,serif;position:relative}.cc-mark:after{content:'';position:absolute;width:6px;height:6px;border-radius:50%;background:var(--mint);right:-3px;top:-3px}.cc-brand strong{display:block;color:#f4fbfa;font-size:15px}.cc-brand span{display:block;color:#8ea9aa;font-size:10px;margin-top:1px}.cc-kicker,.cc-label{font-size:10px;text-transform:uppercase;letter-spacing:.15em;font-weight:750;color:#86a4a6}.cc-nav{display:grid;gap:3px}.cc-nav .cc-kicker{padding:0 10px 8px}.cc-nav a{height:34px;padding:0 10px;display:flex;gap:10px;align-items:center;color:#a9c0bf;text-decoration:none;border-radius:5px;transition:background .16s,color .16s,transform .16s}.cc-nav a:hover{background:var(--navy-2);color:white;transform:translateX(2px)}.cc-nav a.active{background:#20505a;color:#fff;box-shadow:inset 3px 0 var(--mint)}.cc-dot{width:5px;height:5px;border:1px solid #64868a;border-radius:50%}.cc-nav a.active .cc-dot{background:var(--mint);border-color:var(--mint)}
.cc-sidefoot{margin-top:auto;border-top:1px solid #2a4b52;padding:15px 8px 0;display:grid;gap:9px}.cc-sidefoot select{height:32px;width:100%;border:1px solid #355b61;background:#17404a;color:#edf8f5;border-radius:5px;padding:0 8px;font-size:11px}.cc-user{display:flex;gap:8px;align-items:center;margin-top:3px}.cc-avatar{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:#37616a;color:#effcf7;font-weight:750}.cc-user b{display:block;color:#f4fbfa;font-size:12px}.cc-user span{display:block;color:#8fa9aa;font-size:10px}.cc-link{border:0;background:none;text-align:left;padding:0 1px;color:#91aaac;font-size:11px;cursor:pointer}.cc-link:hover{color:#d9f1ea}
.cc-main{min-width:0}.cc-header{height:78px;background:var(--surface);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 29px}.cc-header h1{margin:3px 0 0;font-size:25px;line-height:1;font-weight:780;letter-spacing:-.05em}.cc-header .cc-kicker{color:var(--teal);font-size:9px}.cc-health{display:flex;gap:18px;align-items:center;color:var(--muted);font-size:11px}.cc-health span{display:flex;gap:7px;align-items:center}.cc-health i{width:7px;height:7px;border-radius:50%;background:#72b77b;box-shadow:0 0 0 3px #e0f0e1}.cc-health strong{color:var(--ink);font-weight:750}
.cc-body{padding:20px 29px 35px;max-width:1460px}.cc-tabs{display:flex;gap:2px;overflow:auto;padding:4px;background:var(--surface);border:1px solid var(--line);border-radius:6px}.cc-tabs button{white-space:nowrap;border:0;background:transparent;border-radius:4px;color:#668086;padding:8px 10px;font-size:11px;font-weight:700;cursor:pointer;transition:background .16s,color .16s}.cc-tabs button:hover{background:#edf5f3;color:var(--ink)}.cc-tabs button.on{background:var(--navy);color:#fff}
.cc-context{display:flex;justify-content:space-between;align-items:end;gap:20px;margin:18px 1px 15px}.cc-context h2{font-size:17px;margin:4px 0 0;letter-spacing:-.03em}.cc-context p{margin:0;color:var(--muted);font-size:12px}.cc-context-meta{display:flex;gap:14px;align-items:center;color:var(--quiet);font:10px ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.08em}.cc-save{height:31px;border:1px solid var(--teal);background:var(--teal);color:#fff;border-radius:5px;padding:0 12px;font-size:11px;font-weight:750;cursor:pointer;transition:transform .16s,background .16s}.cc-save:hover{background:var(--teal-deep);transform:translateY(-1px)}.cc-save:focus-visible,.cc-tabs button:focus-visible,.cc-nav a:focus-visible,.cc-link:focus-visible,.cc-toggle:focus-visible{outline:3px solid #b7ddd0;outline-offset:2px}
.cc-overview{display:grid;grid-template-columns:1.1fr .9fr .9fr .9fr;gap:9px;margin-bottom:14px}.cc-metric{background:var(--surface);border:1px solid var(--line);border-radius:6px;padding:11px 13px;min-height:69px}.cc-metric small{display:block;color:var(--quiet);font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:750}.cc-metric strong{display:block;font-size:17px;letter-spacing:-.04em;margin-top:5px}.cc-metric span{display:block;color:#5e927d;font-size:10px;margin-top:2px}.cc-metric.primary{background:#e1f0ea;border-color:#bbd6c9}.cc-metric.primary strong{color:var(--teal-deep)}
.cc-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(300px,.75fr);gap:14px;align-items:start}.cc-card{background:var(--surface);border:1px solid var(--line);border-radius:7px;box-shadow:0 2px 7px #15394309}.cc-card-head{padding:14px 17px 11px;border-bottom:1px solid var(--line-soft);display:flex;justify-content:space-between;align-items:start;gap:12px}.cc-card-head h3{margin:0;font-size:13px;letter-spacing:-.02em}.cc-card-head p{margin:3px 0 0;color:var(--muted);font-size:11px}.cc-code{font:9px ui-monospace,SFMono-Regular,monospace;color:#9aabad;white-space:nowrap}.cc-card-body{padding:15px 17px}
.cc-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.cc-field{display:grid;gap:5px}.cc-field label,.cc-field>span:first-child{font-size:10px;text-transform:uppercase;letter-spacing:.11em;color:#657c80;font-weight:750}.cc-field input,.cc-field select,.cc-field textarea{width:100%;border:1px solid #c7d6d5;background:#f8fbfa;color:var(--ink);border-radius:4px;padding:0 9px;outline:none;transition:border .16s,box-shadow .16s,background .16s}.cc-field input,.cc-field select{height:34px}.cc-field textarea{padding:7px 9px;resize:vertical;line-height:1.55}.cc-field input:focus,.cc-field select:focus,.cc-field textarea:focus{border-color:#5aa7a7;background:#fff;box-shadow:0 0 0 3px #d9eee8}.cc-help{font-size:10px;color:#8a9da0;line-height:1.35}.cc-actions{display:flex;align-items:center;gap:10px;margin-top:14px}.cc-secondary{height:31px;border:1px solid #c4d3d2;background:#fff;color:#647c80;border-radius:4px;padding:0 11px;font-size:11px;font-weight:700;cursor:pointer}.cc-secondary:hover{background:#eef5f3;border-color:#9abdbc}.cc-saved{font-size:10px;color:#438361;animation:cc-in .2s ease-out}@keyframes cc-in{from{opacity:0;transform:translateY(2px)}to{opacity:1;transform:none}}
.cc-toggle{display:grid;grid-template-columns:31px 1fr;gap:10px;align-items:start;border:0;background:none;text-align:left;width:100%;padding:0 0 12px;color:var(--ink);cursor:pointer}.cc-toggle:last-child{padding-bottom:0}.cc-switch{width:29px;height:17px;border:0;border-radius:12px;background:#c1cfce;position:relative;transition:background .18s}.cc-switch:after{content:'';position:absolute;left:3px;top:3px;width:11px;height:11px;border-radius:50%;background:#fff;transition:transform .18s}.cc-toggle.on .cc-switch{background:var(--teal)}.cc-toggle.on .cc-switch:after{transform:translateX(12px)}.cc-toggle strong{display:block;text-align:left;font-size:11px;line-height:1.2}.cc-toggle p{margin:3px 0 0;text-align:left;color:#819498;font-size:10px;line-height:1.35}.cc-rule{border-top:1px solid var(--line-soft);margin:4px 0 13px}.cc-mini{display:grid;gap:11px}.cc-mini .cc-field{gap:4px}.cc-note{background:#f0f6f3;border:1px solid #d5e6df;border-radius:5px;padding:10px 11px;color:#5f7c76;font-size:10px;line-height:1.45;margin-top:14px}.cc-note b{display:block;color:var(--teal-deep);font-size:10px;margin-bottom:3px}.cc-wide{grid-column:1/-1}.cc-side-stack{display:grid;gap:14px}.cc-rail-title{padding:14px 16px 10px;font-size:10px;text-transform:uppercase;letter-spacing:.13em;font-weight:800;color:var(--teal-deep);border-bottom:1px solid var(--line-soft)}.cc-check{display:flex;gap:9px;padding:10px 16px;border-bottom:1px solid var(--line-soft);align-items:start}.cc-check:last-child{border-bottom:0}.cc-check i{width:17px;height:17px;display:grid;place-items:center;border-radius:50%;background:#dceee2;color:#4a9665;font-size:11px;font-style:normal;font-weight:800}.cc-check b{font-size:11px;display:block}.cc-check span{display:block;color:#85999a;font-size:10px;margin-top:2px}.cc-log{padding:12px 16px;display:grid;gap:11px}.cc-log-row{display:grid;grid-template-columns:7px 1fr auto;gap:8px;align-items:start}.cc-log-row i{width:6px;height:6px;margin-top:4px;border-radius:50%;background:#70a8a0}.cc-log-row b{display:block;font-size:10px;font-weight:700}.cc-log-row span{display:block;color:#8a9c9e;font-size:9px;margin-top:2px}.cc-log-row time{color:#9aacad;font:9px ui-monospace,SFMono-Regular,monospace}
@media(max-width:1060px){.cc-overview{grid-template-columns:repeat(2,1fr)}.cc-layout{grid-template-columns:1fr}.cc-side-stack{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){.cc-shell{display:block}.cc-sidebar{min-height:auto;padding:13px}.cc-brand{margin-bottom:10px;padding-bottom:13px}.cc-nav{display:flex;overflow:auto}.cc-nav .cc-kicker,.cc-sidefoot{display:none}.cc-nav a{white-space:nowrap}.cc-header{height:68px;padding:0 16px}.cc-health{display:none}.cc-body{padding:14px 13px 28px}.cc-context{display:block}.cc-context-meta{margin-top:9px}.cc-overview{grid-template-columns:repeat(2,1fr)}.cc-form{grid-template-columns:1fr}.cc-wide{grid-column:auto}.cc-side-stack{display:grid;grid-template-columns:1fr}}
`;

function Toggle({ title, hint, initial = true }: { title: string; hint: string; initial?: boolean }) {
  const [on, setOn] = useState(initial);
  return <button type="button" className={`cc-toggle ${on ? 'on' : ''}`} onClick={() => setOn(!on)} aria-pressed={on}><span className="cc-switch" aria-hidden="true" /><span><strong>{title}</strong><p>{hint}</p></span></button>;
}

function SaveButton({ children }: { children: ReactNode }) {
  const [saved, setSaved] = useState(false);
  return <div className="cc-actions"><button type="button" className="cc-save" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }}>{children}</button>{saved && <span className="cc-saved" role="status">Saved just now</span>}</div>;
}

export function CommandCenter() {
  const [tab, setTab] = useState('Portal');
  const [names, setNames] = useState({ company: 'Greystone Merchant Partners', portal: 'Commission portal', email: 'ops@greystone.com' });
  const [listValues, setListValues] = useState({ frequencies: 'Weekly\nBi-weekly\nMonthly', statuses: 'Performing\nProspecting\nRefi Ready' });
  return <div className="cc-settings"><style>{css}</style><div className="cc-shell">
    <aside className="cc-sidebar"><div className="cc-brand"><div className="cc-mark">G</div><div><strong>Greystone</strong><span>Commission portal</span></div></div>
      <nav className="cc-nav"><div className="cc-kicker">Admin / workspace</div>{nav.map(item => <a href="#settings" className={item === 'Settings' ? 'active' : ''} key={item}><i className="cc-dot" />{item}</a>)}</nav>
      <div className="cc-sidefoot"><div className="cc-label">View as</div><select defaultValue="admin" aria-label="View as"><option value="admin">Admin — master view</option></select><div className="cc-user"><div className="cc-avatar">L</div><div><b>Leor</b><span>Super admin</span></div></div><button type="button" className="cc-link">Change password</button><button type="button" className="cc-link">Two-factor sign-in</button><button type="button" className="cc-link">Sign out</button></div>
    </aside>
    <main className="cc-main"><header className="cc-header"><div><div className="cc-kicker">Admin / command center</div><h1>Settings</h1></div><div className="cc-health"><span><i />All systems operational</span><strong>Last saved 2 min ago</strong></div></header>
      <div className="cc-body"><div className="cc-tabs" role="tablist">{settingsTabs.map(item => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'on' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>
        <div className="cc-context"><div><div className="cc-kicker">Portal controls / active scope</div><h2>System behavior and access</h2><p>Changes here affect every rep, admin and automated message in the portal.</p></div><div className="cc-context-meta"><span>Scope: global</span><span>v2.4</span></div></div>
        <div className="cc-overview"><div className="cc-metric primary"><small>Configuration health</small><strong>Ready to publish</strong><span>All required controls complete</span></div><div className="cc-metric"><small>Active admins</small><strong>04</strong><span>2FA coverage · 75%</span></div><div className="cc-metric"><small>Automations</small><strong>04 / 04</strong><span>Next run · 07:00</span></div><div className="cc-metric"><small>Audit trail</small><strong>12 changes</strong><span>Last 30 days</span></div></div>
        <div className="cc-layout"><div className="cc-card"><div className="cc-card-head"><div><h3>Portal identity</h3><p>Names shown in the sidebar, sign-in screen, emails and authenticator apps.</p></div><span className="cc-code">PORTAL.01</span></div><div className="cc-card-body"><div className="cc-form"><div className="cc-field"><label>Company</label><input value={names.company} onChange={e => setNames({ ...names, company: e.target.value })} /></div><div className="cc-field"><label>Portal name</label><input value={names.portal} onChange={e => setNames({ ...names, portal: e.target.value })} /></div><div className="cc-field"><label>Support email</label><input value={names.email} onChange={e => setNames({ ...names, email: e.target.value })} /><span className="cc-help">Shown to reps when something needs a human</span></div></div><SaveButton>Save names</SaveButton></div></div>
          <div className="cc-side-stack"><section className="cc-card"><div className="cc-rail-title">Control checklist</div><div className="cc-check"><i>✓</i><div><b>Portal identity</b><span>Ready · saved 2 min ago</span></div></div><div className="cc-check"><i>✓</i><div><b>Authentication policy</b><span>Admin 2FA recommended</span></div></div><div className="cc-check"><i>✓</i><div><b>Dropdown integrity</b><span>3 required statuses protected</span></div></div></section><section className="cc-card"><div className="cc-rail-title">Recent activity</div><div className="cc-log"><div className="cc-log-row"><i /><div><b>Leor updated portal name</b><span>Identity controls</span></div><time>2m</time></div><div className="cc-log-row"><i /><div><b>Policy review completed</b><span>Security controls</span></div><time>1d</time></div><div className="cc-log-row"><i /><div><b>Renewal digest sent</b><span>mail.sent · 08:00</span></div><time>1d</time></div></div></section></div>
          <section className="cc-card"><div className="cc-card-head"><div><h3>Automatic emails</h3><p>Each event is logged in the Audit log as <b>mail.sent</b>.</p></div><span className="cc-code">PORTAL.02</span></div><div className="cc-card-body"><Toggle title="Statements when a run is approved" hint="Every rep with lines in the run gets their summary and a link to Pay history." /><Toggle title="Clawback notices" hint="Each rep with a slice hears the amount and that it nets against their next payout." /><Toggle title="Rep questions to admins" hint="When a rep asks about a deal from their drawer, admins get the note by email too." /><Toggle title="Daily renewal digest" hint="Refi-ready and Prospecting deals, to every admin, once a day." /><div className="cc-rule" /><div className="cc-form"><div className="cc-field"><label>Digest goes out at</label><select defaultValue="8"><option value="8">08 your time · 13:00 UTC</option></select></div><div className="cc-field"><label>Playbooks run daily at</label><select defaultValue="7"><option value="7">07 your time · 12:00 UTC</option></select><span className="cc-help">Rules under Settings › Playbooks fire once a day after this hour.</span></div></div><SaveButton>Save email controls</SaveButton><div className="cc-note"><b>Provider credentials are protected</b>The sending address and provider key live in the host's Secrets (MAIL_PROVIDER, MAIL_API_KEY, MAIL_FROM). They never change from here.</div></div></section>
          <section className="cc-card"><div className="cc-card-head"><div><h3>Permissions</h3><p>What reps may do from their portal.</p></div><span className="cc-code">PORTAL.03</span></div><div className="cc-card-body"><Toggle title="Reps can email merchants from a deal" hint="Off hides the button for everyone. Individual reps can still be blocked under Reps › Merchant email." /><Toggle title="Reps can fill in merchant details on their deals" hint="Contact name, email and phone — never the business name or the money. Changes are audited." /><SaveButton>Save permissions</SaveButton></div></section>
          <section className="cc-card"><div className="cc-card-head"><div><h3>Security</h3><p>Passwords, two-factor controls and session duration.</p></div><span className="cc-code">PORTAL.04</span></div><div className="cc-card-body"><Toggle title="Require two-factor for admins" hint="Admins who have not set up an authenticator are held at a setup screen until they do." /><div className="cc-mini"><div className="cc-field"><label>Sign out after inactivity</label><select defaultValue="4"><option value="4">4 hours</option></select><span className="cc-help">Everyone, admins included. The server refuses the old session too.</span></div><div className="cc-field"><label>Remember a device after a two-factor code</label><select defaultValue="14"><option value="14">14 days</option></select><span className="cc-help">The rep still types their password; the code is skipped on a remembered browser.</span></div></div><SaveButton>Save security</SaveButton></div></section>
          <section className="cc-card cc-wide"><div className="cc-card-head"><div><h3>Dropdown lists</h3><p>One per line · commission statuses are fixed because they drive collection.</p></div><span className="cc-code">PORTAL.05</span></div><div className="cc-card-body"><div className="cc-form"><div className="cc-field"><label>Payment frequencies</label><textarea rows={4} value={listValues.frequencies} onChange={e => setListValues({ ...listValues, frequencies: e.target.value })} /></div><div className="cc-field"><label>Deal statuses</label><textarea rows={4} value={listValues.statuses} onChange={e => setListValues({ ...listValues, statuses: e.target.value })} /><span className="cc-help">Keep Performing, Prospecting and Refi Ready — the portal sets those itself.</span></div><div className="cc-note" style={{ marginTop: 0 }}><b>Protected values</b>Performing · Prospecting · Refi Ready<br />These statuses power collection and renewal rules.</div></div><SaveButton>Save lists</SaveButton></div></section>
        </div>
      </div>
    </main>
  </div></div>;
}