import { useState, type ReactNode } from 'react';

const destinations = ['Funding overview', 'Master deals', 'Merchants', 'Run payroll', 'Renewals', 'Books', 'Rep roster', 'Settings', 'Audit log'];
const settingsTabs = ['Portal', 'Lenders', 'Referral partners', 'Product rules', 'Teams', 'Reps', 'CRM & thresholds', 'Playbooks', 'Import from sheet', 'Lender remittance'];

const styles = `
.focus-settings{--ink:#172f35;--muted:#6d8184;--faint:#91a2a4;--line:#d8e5df;--line-soft:#e9f0ed;--paper:#f3f7f4;--surface:#fff;--rail:#e9f1ec;--nav:#173b3d;--nav-deep:#123335;--teal:#1a6e6b;--teal-dark:#125854;--teal-soft:#dcefeb;--mint:#b8d9bd;--amber:#d28c42;min-height:100vh;background:var(--paper);color:var(--ink);font:13px/1.42 'DM Sans',ui-sans-serif,system-ui,sans-serif;letter-spacing:-.012em;-webkit-font-smoothing:antialiased}
.focus-settings *{box-sizing:border-box}.focus-settings button,.focus-settings input,.focus-settings select,.focus-settings textarea{font:inherit}.focus-shell{display:grid;grid-template-columns:226px 196px minmax(0,1fr);min-height:100vh}
.focus-nav{background:var(--nav-deep);color:#dbe9e3;padding:19px 12px 15px;display:flex;flex-direction:column}.focus-brand{display:flex;align-items:center;gap:10px;padding:1px 9px 20px;border-bottom:1px solid #2b5050;margin-bottom:17px}.focus-mark{width:28px;height:28px;border:1px solid #91c0b4;border-radius:8px;display:grid;place-items:center;color:#d8f0e6;font:700 16px Georgia,serif;position:relative}.focus-mark:after{content:'';width:5px;height:5px;background:var(--mint);border-radius:50%;position:absolute;right:-3px;top:-3px}.focus-brand strong{display:block;color:#f4fbf7;font-size:15px;letter-spacing:.01em}.focus-brand span{display:block;color:#90ada9;font-size:11px;margin-top:1px}.focus-eyebrow,.focus-label{font-size:10px;font-weight:750;letter-spacing:.14em;text-transform:uppercase;color:#8da8a4}.focus-navlist{display:grid;gap:3px}.focus-navlist .focus-eyebrow{padding:0 10px 8px}.focus-navlist a{height:34px;padding:0 10px;display:flex;align-items:center;gap:10px;color:#a9c2bd;text-decoration:none;border-radius:6px;transition:background .16s,color .16s,transform .16s}.focus-navlist a:hover{background:#245051;color:#fff;transform:translateX(2px)}.focus-navlist a.active{background:#275856;color:#fff;box-shadow:inset 3px 0 var(--mint)}.focus-navlist a i{width:5px;height:5px;border-radius:50%;border:1px solid #6c9791}.focus-navlist a.active i{background:var(--mint);border-color:var(--mint)}.focus-sidefoot{margin-top:auto;border-top:1px solid #2b5050;padding:14px 8px 0;display:grid;gap:9px}.focus-sidefoot select{height:32px;width:100%;background:#204748;color:#e4f1ed;border:1px solid #416766;border-radius:5px;padding:0 8px;font-size:11px}.focus-user{display:flex;gap:9px;align-items:center;padding:3px 2px}.focus-avatar{width:27px;height:27px;border-radius:50%;background:#3c6966;color:#e5f8ef;display:grid;place-items:center;font-size:12px;font-weight:700}.focus-user b{display:block;font-size:12px;color:#f2f8f6}.focus-user span{display:block;color:#93aeaa;font-size:11px}.focus-link{border:0;background:transparent;text-align:left;padding:0 2px;color:#91aaa6;font-size:11px;cursor:pointer}.focus-link:hover{color:#d8f0e6}
.focus-sectionrail{background:var(--rail);border-right:1px solid #d3e2dc;padding:24px 15px}.focus-sectionrail .focus-label{color:#6d8581;padding:0 10px}.focus-sectionrail h2{margin:7px 10px 3px;font-size:17px;letter-spacing:-.035em}.focus-sectionrail p{margin:0 10px 20px;color:#80918f;font-size:11px;line-height:1.4}.focus-settingsnav{display:grid;gap:3px}.focus-settingsnav button{border:0;background:transparent;color:#627976;text-align:left;padding:9px 10px;border-radius:5px;cursor:pointer;display:flex;align-items:center;justify-content:space-between;transition:background .16s,color .16s}.focus-settingsnav button:hover{background:#dce9e3;color:var(--ink)}.focus-settingsnav button.on{background:var(--surface);color:var(--teal-dark);font-weight:750;box-shadow:0 1px 4px #28544b12}.focus-settingsnav button.on:after{content:'•';color:var(--teal);font-size:17px;line-height:0}.focus-railnote{border-top:1px solid #cfdfd8;margin:22px 10px 0;padding-top:14px;color:#7c908c;font-size:10px;line-height:1.5}.focus-railnote b{display:block;color:#5c7570;font-size:10px;text-transform:uppercase;letter-spacing:.11em;margin-bottom:4px}
.focus-main{min-width:0}.focus-header{height:78px;background:var(--surface);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 30px}.focus-header h1{font-size:24px;line-height:1.05;margin:4px 0 0;font-weight:780;letter-spacing:-.05em}.focus-header .focus-eyebrow{color:var(--teal);font-size:9px}.focus-status{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:11px}.focus-status i{width:7px;height:7px;background:#68ad78;border-radius:50%;box-shadow:0 0 0 3px #e3f1e6}
.focus-content{padding:25px 30px 38px;max-width:960px}.focus-kicker{display:flex;align-items:flex-start;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:17px;margin-bottom:17px}.focus-kicker h2{font-size:18px;letter-spacing:-.035em;margin:0 0 4px}.focus-kicker p{margin:0;color:var(--muted);font-size:12px}.focus-revision{font:10px ui-monospace,SFMono-Regular,monospace;text-transform:uppercase;letter-spacing:.08em;color:#849694;padding-top:4px}.focus-card{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:19px 20px 17px;box-shadow:0 3px 13px #27544b0b;margin-bottom:12px}.focus-cardhead{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;border-bottom:1px solid var(--line-soft);padding-bottom:12px;margin-bottom:15px}.focus-card h3{font-size:14px;margin:0;font-weight:780;letter-spacing:-.015em}.focus-cardhead span{display:block;margin-top:3px;color:#859593;font-size:11px}.focus-code{color:#9aa9a5;font:10px ui-monospace,SFMono-Regular,monospace;white-space:nowrap}.focus-form{display:grid;gap:12px}.focus-form.two{grid-template-columns:repeat(2,minmax(0,1fr));gap:13px 16px}.focus-field{display:grid;gap:5px}.focus-field label,.focus-field>span:first-child{font-size:10px;font-weight:750;letter-spacing:.1em;text-transform:uppercase;color:#6b817d}.focus-field input,.focus-field select,.focus-field textarea{width:100%;border:1px solid #cbdad4;background:#fbfdfc;border-radius:5px;padding:0 10px;color:var(--ink);outline:none;transition:border .16s,box-shadow .16s,background .16s}.focus-field input,.focus-field select{height:34px}.focus-field textarea{padding:8px 10px;resize:vertical;line-height:1.65}.focus-field input:focus,.focus-field select:focus,.focus-field textarea:focus{border-color:#559a91;background:#fff;box-shadow:0 0 0 3px #dcefeb}.focus-help{font-size:11px;color:#91a09d;line-height:1.35}.focus-actions{display:flex;align-items:center;gap:10px;margin-top:14px}.focus-btn{height:33px;border-radius:5px;padding:0 12px;border:1px solid #c5d5cf;background:#fff;color:#627773;font-weight:750;font-size:11px;cursor:pointer;transition:background .16s,transform .16s,border .16s}.focus-btn:hover{transform:translateY(-1px);border-color:#8bb4aa;background:#f5faf7}.focus-btn.primary{background:var(--teal);border-color:var(--teal);color:#fff}.focus-btn.primary:hover{background:var(--teal-dark);border-color:var(--teal-dark)}.focus-saved{color:#3d8660;font-size:11px;animation:focus-in .2s ease-out}@keyframes focus-in{from{opacity:0;transform:translateY(2px)}to{opacity:1;transform:none}}
.focus-toggle{display:grid;grid-template-columns:31px 1fr;gap:10px;align-items:start;padding:0 0 12px}.focus-toggle:last-of-type{padding-bottom:0}.focus-toggle button{width:30px;height:18px;border:0;border-radius:10px;background:#c5d1cc;padding:0;position:relative;cursor:pointer;transition:background .18s}.focus-toggle button:after{content:'';position:absolute;top:3px;left:3px;width:12px;height:12px;background:#fff;border-radius:50%;transition:transform .18s}.focus-toggle button.on{background:var(--teal)}.focus-toggle button.on:after{transform:translateX(12px)}.focus-toggle button:focus-visible,.focus-settingsnav button:focus-visible,.focus-btn:focus-visible,.focus-link:focus-visible{outline:2px solid #a9cfc2;outline-offset:2px}.focus-toggle strong{font-size:12px;display:block;line-height:1.25}.focus-toggle p{margin:3px 0 0;color:#899b97;font-size:11px;line-height:1.35}.focus-rule{border-top:1px solid var(--line-soft);margin:3px 0 13px}.focus-footnote{margin:12px 0 0;color:#94a29f;font-size:10px;line-height:1.45}
@media(max-width:1050px){.focus-shell{grid-template-columns:210px 174px minmax(0,1fr)}.focus-header,.focus-content{padding-left:22px;padding-right:22px}}@media(max-width:780px){.focus-shell{display:block}.focus-nav{min-height:auto;padding:13px}.focus-brand{margin-bottom:10px;padding-bottom:13px}.focus-navlist{display:flex;overflow:auto}.focus-navlist .focus-eyebrow,.focus-sidefoot{display:none}.focus-navlist a{white-space:nowrap}.focus-sectionrail{border-right:0;border-bottom:1px solid #d3e2dc;padding:14px}.focus-sectionrail h2,.focus-sectionrail p{display:none}.focus-settingsnav{display:flex;overflow:auto}.focus-settingsnav button{white-space:nowrap}.focus-railnote{display:none}.focus-header{height:70px;padding:0 16px}.focus-status{display:none}.focus-content{padding:17px 14px 28px}.focus-kicker{display:block}.focus-revision{margin-top:9px}.focus-form.two{grid-template-columns:1fr}}
`;

function Toggle({ title, hint, initial = true }: { title: string; hint: string; initial?: boolean }) {
  const [on, setOn] = useState(initial);
  return <div className="focus-toggle"><button type="button" aria-label={`${title}: ${on ? 'on' : 'off'}`} aria-pressed={on} className={on ? 'on' : ''} onClick={() => setOn(!on)} /><div><strong>{title}</strong><p>{hint}</p></div></div>;
}

function SaveButton({ children = 'Save changes' }: { children?: ReactNode }) {
  const [saved, setSaved] = useState(false);
  return <div className="focus-actions"><button className="focus-btn primary" type="button" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }}>{children}</button>{saved && <span className="focus-saved" role="status">Saved just now</span>}</div>;
}

function Card({ title, note, code, children }: { title: string; note: string; code: string; children: ReactNode }) {
  return <section className="focus-card"><div className="focus-cardhead"><div><h3>{title}</h3><span>{note}</span></div><div className="focus-code">{code}</div></div>{children}</section>;
}

export function FocusedWorkspace() {
  const [section, setSection] = useState('Portal');
  const [destination, setDestination] = useState('Settings');
  const [names, setNames] = useState({ company: 'Greystone Merchant Partners', portal: 'Commission portal', email: 'ops@greystone.com' });
  return <div className="focus-settings"><style>{styles}</style><div className="focus-shell">
    <aside className="focus-nav">
      <div className="focus-brand"><div className="focus-mark">G</div><div><strong>Greystone</strong><span>Commission portal</span></div></div>
      <nav className="focus-navlist" aria-label="Primary navigation"><div className="focus-eyebrow">Admin / workspace</div>{destinations.map(item => <a href={`#${item.toLowerCase().replaceAll(' ', '-')}`} className={destination === item ? 'active' : ''} onClick={() => setDestination(item)} key={item}><i />{item}</a>)}</nav>
      <div className="focus-sidefoot"><div className="focus-label">View as</div><select defaultValue="admin" aria-label="View as"><option value="admin">Admin — master view</option></select><div className="focus-user"><div className="focus-avatar">L</div><div><b>Leor</b><span>Super admin</span></div></div><button className="focus-link" type="button">Change password</button><button className="focus-link" type="button">Two-factor sign-in</button><button className="focus-link" type="button">Sign out</button></div>
    </aside>
    <aside className="focus-sectionrail">
      <div className="focus-label">Settings / configure</div><h2>Control center</h2><p>Choose one operating area to work in. Your place is remembered.</p>
      <nav className="focus-settingsnav" aria-label="Settings sections">{settingsTabs.map(item => <button type="button" className={section === item ? 'on' : ''} onClick={() => setSection(item)} key={item}>{item}</button>)}</nav>
      <div className="focus-railnote"><b>Focused view</b>Portal controls are open. Other configuration areas stay one click away.</div>
    </aside>
    <main className="focus-main"><header className="focus-header"><div><div className="focus-eyebrow">Admin / controls / {section}</div><h1>Settings</h1></div><div className="focus-status"><i />All systems operational</div></header>
      <div className="focus-content"><div className="focus-kicker"><div><h2>{section}</h2><p>Names, automatic emails, security and dropdown lists — the operating surface for how the portal behaves.</p></div><span className="focus-revision">PORTAL CONFIGURATION · V2.4</span></div>
        <Card title="Names" note="Sidebar, sign-in screen, emails and authenticator apps" code="PORTAL.01"><div className="focus-form two">
          <div className="focus-field"><label>Company</label><input value={names.company} onChange={e => setNames({ ...names, company: e.target.value })} /></div>
          <div className="focus-field"><label>Portal name</label><input value={names.portal} onChange={e => setNames({ ...names, portal: e.target.value })} /></div>
          <div className="focus-field"><label>Support email</label><input value={names.email} onChange={e => setNames({ ...names, email: e.target.value })} /><span className="focus-help">Shown to reps when something needs a human</span></div>
        </div><SaveButton>Save names</SaveButton></Card>
        <Card title="Automatic emails" note="Each one is logged in the Audit log as mail.sent" code="PORTAL.02">
          <Toggle title="Statements when a run is approved" hint="Every rep with lines in the run gets their summary and a link to Pay history." /><Toggle title="Clawback notices" hint="Each rep with a slice hears the amount and that it nets against their next payout." /><Toggle title="Rep questions to admins" hint="When a rep asks about a deal from their drawer, admins get the note by email too." /><Toggle title="Daily renewal digest" hint="Refi-ready and Prospecting deals, to every admin, once a day." />
          <div className="focus-rule" /><div className="focus-form two"><div className="focus-field"><label>Digest goes out at</label><select defaultValue="8"><option value="8">08 your time · 13:00 UTC</option></select></div><div className="focus-field"><label>Playbooks run daily at</label><select defaultValue="7"><option value="7">07 your time · 12:00 UTC</option></select><span className="focus-help">Rules under Settings › Playbooks fire once a day after this hour; rep emails roll up into one message.</span></div></div><SaveButton>Save email controls</SaveButton><p className="focus-footnote">The sending address and provider key live in the host's Secrets (MAIL_PROVIDER, MAIL_API_KEY, MAIL_FROM) — those never change from here.</p>
        </Card>
        <Card title="Permissions" note="What reps may do from their portal" code="PORTAL.03"><Toggle title="Reps can email merchants from a deal" hint="Off hides the button for everyone. On, you can still block individual reps under Reps › Merchant email. Emails go out under the rep's name from the templates under Playbooks." /><Toggle title="Reps can fill in merchant details on their deals" hint="Contact name, email and phone — never the business name or the money. Saved to the merchant record and audited, so Merchants, renewals and playbooks see it too." /><SaveButton>Save permissions</SaveButton></Card>
        <Card title="Security" note="Passwords and two-factor controls" code="PORTAL.04"><Toggle title="Require two-factor for admins" hint="Admins who have not set up an authenticator are held at a setup screen until they do. Turn on your own first." /><div className="focus-form two"><div className="focus-field"><label>Sign out after inactivity</label><select defaultValue="4"><option value="4">4 hours</option></select><span className="focus-help">Everyone, admins included. A tab left open returns to the sign-in screen; the server refuses the old session too.</span></div><div className="focus-field"><label>Remember a device after a two-factor code</label><select defaultValue="14"><option value="14">14 days</option></select><span className="focus-help">The rep still types their password; the code is skipped on a remembered browser.</span></div></div><SaveButton>Save security</SaveButton></Card>
        <Card title="Dropdown lists" note="One per line · commission statuses are fixed because they drive collection" code="PORTAL.05"><div className="focus-form two"><div className="focus-field"><label>Payment frequencies</label><textarea rows={4} defaultValue={'Weekly\nBi-weekly\nMonthly'} /></div><div className="focus-field"><label>Deal statuses</label><textarea rows={4} defaultValue={'Performing\nProspecting\nRefi Ready'} /><span className="focus-help">Keep Performing, Prospecting and Refi Ready — the portal sets those itself.</span></div></div><SaveButton>Save lists</SaveButton></Card>
      </div>
    </main>
  </div></div>;
}