import { useState, type ReactNode } from 'react';

const destinations = ['Funding overview', 'Master deals', 'Merchants', 'Run payroll', 'Renewals', 'Books', 'Rep roster', 'Settings', 'Audit log'];
const settingsTabs = ['Portal', 'Lenders', 'Referral partners', 'Product rules', 'Teams', 'Reps', 'CRM & thresholds', 'Playbooks', 'Import from sheet', 'Lender remittance'];

const css = `
.mcd{--ink:#1d2d32;--muted:#687d7d;--quiet:#8da09d;--paper:#f4f8f3;--surface:#fffdf8;--line:#d7e2d8;--teal:#14746d;--teal-deep:#0d554f;--aqua:#d6eeea;--yellow:#f0d879;--coral:#d7775f;--blue:#dce9f1;min-height:100vh;background:var(--paper);color:var(--ink);font:13px/1.4 'DM Sans',ui-sans-serif,system-ui,sans-serif;letter-spacing:-.012em;-webkit-font-smoothing:antialiased}
.mcd *{box-sizing:border-box}.mcd button,.mcd input,.mcd select,.mcd textarea{font:inherit}
.mcd-top{height:72px;background:#fffdf7;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 28px;gap:30px;position:sticky;top:0;z-index:2}
.mcd-brand{display:flex;align-items:center;gap:10px;min-width:188px}.mcd-mark{width:31px;height:31px;border:2px solid var(--teal);color:var(--teal);display:grid;place-items:center;font:700 17px Georgia,serif;transform:rotate(-8deg);position:relative}.mcd-mark:after{content:'';width:6px;height:6px;background:var(--coral);position:absolute;right:-4px;top:-4px;border-radius:50%}.mcd-brand strong{display:block;font-size:15px;letter-spacing:.01em}.mcd-brand span{display:block;color:var(--quiet);font-size:10px;margin-top:1px}
.mcd-primary{display:flex;align-items:center;gap:4px;overflow:auto}.mcd-primary button{border:0;background:transparent;color:#6c807e;padding:8px 10px;white-space:nowrap;cursor:pointer;border-bottom:2px solid transparent}.mcd-primary button:hover,.mcd-primary button.active{color:var(--teal-deep);border-color:var(--teal)}.mcd-topright{margin-left:auto;display:flex;align-items:center;gap:14px;color:var(--muted);font-size:11px;white-space:nowrap}.mcd-dot{width:7px;height:7px;border-radius:50%;background:#69a871;box-shadow:0 0 0 3px #e1efe0}.mcd-avatar{width:30px;height:30px;border-radius:50%;background:#d9ebe2;color:var(--teal-deep);display:grid;place-items:center;font-weight:800}
.mcd-frame{display:grid;grid-template-columns:252px minmax(0,1fr);min-height:calc(100vh - 72px)}.mcd-index{border-right:1px solid var(--line);padding:25px 18px 20px;background:#eef5ef;display:flex;flex-direction:column}.mcd-index-kicker,.mcd-eyebrow,.mcd-label{font-size:10px;letter-spacing:.15em;text-transform:uppercase;font-weight:800;color:#6a8580}.mcd-index h1{font-size:28px;line-height:1;margin:10px 0 7px;letter-spacing:-.065em}.mcd-index p{color:var(--muted);font-size:11px;line-height:1.45;margin:0 10px 24px 0}.mcd-modules{display:grid;gap:3px}.mcd-module{display:flex;align-items:center;gap:10px;border:0;background:transparent;text-align:left;padding:9px 10px;color:#647976;border-radius:4px;cursor:pointer}.mcd-module:hover{background:#e1eee6;color:var(--ink)}.mcd-module.active{background:#fffdf8;color:var(--teal-deep);font-weight:800;box-shadow:0 2px 7px #234b3712}.mcd-module b{width:22px;height:22px;display:grid;place-items:center;border:1px solid #b9cec2;border-radius:4px;color:#6d8b82;font:10px ui-monospace,monospace}.mcd-module.active b{background:var(--teal);border-color:var(--teal);color:#fff}.mcd-index-foot{margin-top:auto;padding:14px 10px 0;border-top:1px solid #d3e2d7;color:#81958e;font-size:10px;line-height:1.5}.mcd-index-foot strong{display:block;color:#4e7068;text-transform:uppercase;letter-spacing:.12em;font-size:9px;margin-bottom:4px}
.mcd-work{padding:25px 31px 42px;min-width:0}.mcd-workhead{display:flex;align-items:flex-end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:17px;margin-bottom:16px}.mcd-workhead h2{font-size:22px;letter-spacing:-.05em;margin:6px 0 3px}.mcd-workhead p{margin:0;color:var(--muted);font-size:12px}.mcd-revision{font:10px ui-monospace,monospace;color:#83958f;letter-spacing:.1em;text-transform:uppercase}
.mcd-deck{display:grid;grid-template-columns:minmax(0,1.38fr) minmax(280px,.62fr);gap:15px;align-items:start}.mcd-stack{display:grid;gap:15px}.mcd-modulecard{background:var(--surface);border:1px solid var(--line);border-radius:3px;box-shadow:4px 4px 0 #dce8dd;padding:17px 18px}.mcd-modulecard.tinted{background:#e4f2ed;border-color:#c1ded2;box-shadow:4px 4px 0 #cbded2}.mcd-cardhead{display:flex;justify-content:space-between;gap:14px;border-bottom:1px solid #e4ece5;padding-bottom:11px;margin-bottom:14px}.mcd-cardhead h3{margin:0;font-size:14px;letter-spacing:-.02em}.mcd-cardhead p{margin:3px 0 0;font-size:11px;color:var(--muted)}.mcd-code{color:#9aa9a1;font:10px ui-monospace,monospace;white-space:nowrap}
.mcd-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.mcd-field{display:grid;gap:5px}.mcd-field label,.mcd-field>span:first-child{font-size:10px;color:#718680;letter-spacing:.1em;text-transform:uppercase;font-weight:800}.mcd-field input,.mcd-field select,.mcd-field textarea{width:100%;border:1px solid #cbdacf;background:#fffefb;border-radius:2px;padding:0 9px;color:var(--ink);outline:none}.mcd-field input,.mcd-field select{height:34px}.mcd-field textarea{padding:8px 9px;resize:vertical;line-height:1.55}.mcd-field input:focus,.mcd-field select:focus,.mcd-field textarea:focus{border-color:#55a79a;box-shadow:0 0 0 3px #d9eee8}.mcd-help{font-size:10px;color:#8a9b95;line-height:1.35}.mcd-actions{display:flex;align-items:center;gap:10px;margin-top:14px}.mcd-save{border:0;background:var(--teal);color:#fff;height:32px;padding:0 13px;border-radius:2px;font-size:11px;font-weight:800;cursor:pointer}.mcd-save:hover{background:var(--teal-deep);transform:translateY(-1px)}.mcd-saved{color:#3d8763;font-size:11px}.mcd-toggle{display:grid;grid-template-columns:30px 1fr;gap:10px;padding-bottom:12px}.mcd-toggle:last-of-type{padding-bottom:0}.mcd-toggle button{width:28px;height:17px;background:#c4d1c9;border:0;border-radius:10px;position:relative;cursor:pointer}.mcd-toggle button:after{content:'';position:absolute;width:11px;height:11px;left:3px;top:3px;background:#fff;border-radius:50%;transition:transform .18s}.mcd-toggle button.on{background:var(--teal)}.mcd-toggle button.on:after{transform:translateX(11px)}.mcd-toggle strong{font-size:11px;line-height:1.25;display:block}.mcd-toggle p{font-size:10px;color:#82958f;margin:3px 0 0;line-height:1.35}.mcd-rule{border-top:1px solid #e3ebe4;margin:4px 0 13px}.mcd-footnote{color:#8b9b95;font-size:10px;line-height:1.45;margin:12px 0 0}
.mcd-aside{display:grid;gap:15px}.mcd-signal{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mcd-stat{background:#fffdf8;border:1px solid var(--line);padding:12px 13px;min-height:76px}.mcd-stat:first-child{background:var(--yellow);border-color:#e1c96c}.mcd-stat small{display:block;color:#61766f;font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.mcd-stat strong{display:block;font-size:18px;letter-spacing:-.05em;margin-top:6px}.mcd-stat span{display:block;font-size:10px;color:#678178;margin-top:2px}.mcd-legend{background:#243e3b;color:#e7f1e8;padding:16px}.mcd-legend h3{font-size:12px;margin:0 0 10px}.mcd-legend-row{display:flex;align-items:center;gap:8px;font-size:10px;color:#b7cebf;padding:6px 0;border-bottom:1px solid #43605a}.mcd-legend-row:last-child{border-bottom:0}.mcd-legend-row i{width:8px;height:8px;background:var(--yellow);display:block}.mcd-legend-row:nth-child(3) i{background:#91c8bd}.mcd-legend-row:nth-child(4) i{background:#d9856d}.mcd-note{background:#f7ead7;border:1px solid #ecd5b4;padding:13px;color:#7a654d;font-size:10px;line-height:1.45}.mcd-note b{display:block;text-transform:uppercase;letter-spacing:.1em;font-size:9px;color:#a16b35;margin-bottom:4px}
.mcd:focus-within button:focus-visible,.mcd:focus-within input:focus-visible,.mcd:focus-within select:focus-visible,.mcd:focus-within textarea:focus-visible{outline:2px solid #77b7aa;outline-offset:2px}
@media(max-width:980px){.mcd-top{gap:14px;padding:0 16px}.mcd-primary button{padding:8px 6px}.mcd-frame{grid-template-columns:210px minmax(0,1fr)}.mcd-work{padding:22px 20px}.mcd-form{grid-template-columns:1fr 1fr}.mcd-deck{grid-template-columns:1fr}.mcd-aside{grid-template-columns:1fr 1fr}.mcd-legend,.mcd-note{min-height:100%}}
@media(max-width:700px){.mcd-top{height:auto;min-height:68px;flex-wrap:wrap;padding:12px 14px}.mcd-brand{min-width:auto}.mcd-primary{order:3;width:100%}.mcd-topright{display:none}.mcd-frame{display:block}.mcd-index{padding:17px 14px;border-right:0;border-bottom:1px solid var(--line)}.mcd-index h1,.mcd-index p,.mcd-index-foot{display:none}.mcd-modules{display:flex;overflow:auto}.mcd-module{white-space:nowrap}.mcd-work{padding:18px 14px 30px}.mcd-workhead{display:block}.mcd-revision{display:block;margin-top:10px}.mcd-form{grid-template-columns:1fr}.mcd-aside{display:block}.mcd-aside>*{margin-bottom:12px}.mcd-signal{grid-template-columns:1fr 1fr}}
`;

function Toggle({ title, hint, initial = true }: { title: string; hint: string; initial?: boolean }) {
  const [on, setOn] = useState(initial);
  return <div className="mcd-toggle"><button type="button" className={on ? 'on' : ''} aria-label={`${title}: ${on ? 'on' : 'off'}`} aria-pressed={on} onClick={() => setOn(!on)} /><div><strong>{title}</strong><p>{hint}</p></div></div>;
}

function SaveButton({ children }: { children: ReactNode }) {
  const [saved, setSaved] = useState(false);
  return <div className="mcd-actions"><button className="mcd-save" type="button" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }}>{children}</button>{saved && <span className="mcd-saved" role="status">Saved just now</span>}</div>;
}

function ModuleCard({ title, note, code, children, className = '' }: { title: string; note: string; code: string; children: ReactNode; className?: string }) {
  return <section className={`mcd-modulecard ${className}`}><div className="mcd-cardhead"><div><h3>{title}</h3><p>{note}</p></div><span className="mcd-code">{code}</span></div>{children}</section>;
}

export function ModularControlDeck() {
  const [tab, setTab] = useState('Portal');
  const [destination, setDestination] = useState('Settings');
  const [names, setNames] = useState({ company: 'Greystone Merchant Partners', portal: 'Commission portal', email: 'ops@greystone.com' });
  const [lists, setLists] = useState({ frequencies: 'Weekly\nBi-weekly\nMonthly', statuses: 'Performing\nProspecting\nRefi Ready' });
  return <div className="mcd"><style>{css}</style>
    <header className="mcd-top"><div className="mcd-brand"><div className="mcd-mark">G</div><div><strong>Greystone</strong><span>Commission portal</span></div></div>
      <nav className="mcd-primary" aria-label="Primary navigation">{destinations.map(item => <button type="button" className={destination === item ? 'active' : ''} onClick={() => setDestination(item)} key={item}>{item}</button>)}</nav>
      <div className="mcd-topright"><span className="mcd-dot" />Operational <div className="mcd-avatar">L</div></div>
    </header>
    <div className="mcd-frame"><aside className="mcd-index"><div className="mcd-index-kicker">Settings / modules</div><h1>Control deck</h1><p>Configure the operating surfaces that keep commissions moving.</p><nav className="mcd-modules" aria-label="Settings sections">{settingsTabs.map((item, index) => <button type="button" className={`mcd-module ${tab === item ? 'active' : ''}`} onClick={() => setTab(item)} key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span></button>)}</nav><div className="mcd-index-foot"><strong>Workspace view</strong>Admin — master view<br />Leor · Super admin</div></aside>
      <main className="mcd-work"><div className="mcd-workhead"><div><div className="mcd-eyebrow">Module {String(settingsTabs.indexOf(tab) + 1).padStart(2, '0')} / global scope</div><h2>{tab}</h2><p>Portal identity, behavior and access controls in one visible system.</p></div><span className="mcd-revision">CONFIGURATION · V2.4</span></div>
        <div className="mcd-deck"><div className="mcd-stack">
          <ModuleCard title="Names" note="Sidebar, sign-in screen, emails and authenticator apps" code="PORTAL.01" className="tinted"><div className="mcd-form"><div className="mcd-field"><label>Company</label><input value={names.company} onChange={e => setNames({ ...names, company: e.target.value })} /></div><div className="mcd-field"><label>Portal name</label><input value={names.portal} onChange={e => setNames({ ...names, portal: e.target.value })} /></div><div className="mcd-field"><label>Support email</label><input value={names.email} onChange={e => setNames({ ...names, email: e.target.value })} /><span className="mcd-help">Shown to reps when something needs a human</span></div></div><SaveButton>Save names</SaveButton></ModuleCard>
          <ModuleCard title="Automatic emails" note="Each one is logged in the Audit log as mail.sent" code="PORTAL.02"><Toggle title="Statements when a run is approved" hint="Every rep with lines in the run gets their summary and a link to Pay history." /><Toggle title="Clawback notices" hint="Each rep with a slice hears the amount and that it nets against their next payout." /><Toggle title="Rep questions to admins" hint="When a rep asks about a deal from their drawer, admins get the note by email too." /><Toggle title="Daily renewal digest" hint="Refi-ready and Prospecting deals, to every admin, once a day." /><div className="mcd-rule" /><div className="mcd-form"><div className="mcd-field"><label>Digest goes out at</label><select defaultValue="8"><option value="8">08 your time · 13:00 UTC</option></select></div><div className="mcd-field"><label>Playbooks run daily at</label><select defaultValue="7"><option value="7">07 your time · 12:00 UTC</option></select><span className="mcd-help">Rules under Settings › Playbooks fire once a day after this hour; rep emails roll up into one message.</span></div></div><SaveButton>Save email controls</SaveButton><p className="mcd-footnote">The sending address and provider key live in the host's Secrets (MAIL_PROVIDER, MAIL_API_KEY, MAIL_FROM) — those never change from here.</p></ModuleCard>
          <ModuleCard title="Permissions" note="What reps may do from their portal" code="PORTAL.03"><Toggle title="Reps can email merchants from a deal" hint="Off hides the button for everyone. On, you can still block individual reps under Reps › Merchant email. Emails go out under the rep's name from the templates under Playbooks." /><Toggle title="Reps can fill in merchant details on their deals" hint="Contact name, email and phone — never the business name or the money. Saved to the merchant record and audited, so Merchants, renewals and playbooks see it too." /><SaveButton>Save permissions</SaveButton></ModuleCard>
        </div><aside className="mcd-aside"><div className="mcd-signal"><div className="mcd-stat"><small>Deck health</small><strong>Ready</strong><span>All required controls complete</span></div><div className="mcd-stat"><small>Audit trail</small><strong>12</strong><span>changes · last 30 days</span></div></div>
          <ModuleCard title="Security" note="Passwords and two-factor controls" code="PORTAL.04"><Toggle title="Require two-factor for admins" hint="Admins who have not set up an authenticator are held at a setup screen until they do. Turn on your own first." /><div className="mcd-field"><label>Sign out after inactivity</label><select defaultValue="4"><option value="4">4 hours</option></select><span className="mcd-help">Everyone, admins included. A tab left open returns to the sign-in screen; the server refuses the old session too.</span></div><div className="mcd-field" style={{ marginTop: 12 }}><label>Remember a device after a two-factor code</label><select defaultValue="14"><option value="14">14 days</option></select><span className="mcd-help">The rep still types their password; the code is skipped on a remembered browser.</span></div><SaveButton>Save security</SaveButton></ModuleCard>
          <div className="mcd-legend"><h3>Module legend</h3><div className="mcd-legend-row"><i />Identity & access</div><div className="mcd-legend-row"><i />Automated operations</div><div className="mcd-legend-row"><i />Protected system values</div></div>
          <ModuleCard title="Dropdown lists" note="One per line · commission statuses are fixed because they drive collection" code="PORTAL.05"><div className="mcd-field"><label>Payment frequencies</label><textarea rows={3} value={lists.frequencies} onChange={e => setLists({ ...lists, frequencies: e.target.value })} /></div><div className="mcd-field" style={{ marginTop: 12 }}><label>Deal statuses</label><textarea rows={3} value={lists.statuses} onChange={e => setLists({ ...lists, statuses: e.target.value })} /><span className="mcd-help">Keep Performing, Prospecting and Refi Ready — the portal sets those itself.</span></div><SaveButton>Save lists</SaveButton></ModuleCard>
          <div className="mcd-note"><b>Protected values</b>Performing · Prospecting · Refi Ready<br />These statuses power collection and renewal rules.</div>
        </aside></div>
      </main></div>
  </div>;
}