import { useState, type ReactNode } from 'react';

const destinations = ['Funding overview', 'Master deals', 'Merchants', 'Run payroll', 'Renewals', 'Books', 'Rep roster', 'Settings', 'Audit log'];
const settingsTabs = ['Portal', 'Lenders', 'Referral partners', 'Product rules', 'Teams', 'Reps', 'CRM & thresholds', 'Playbooks', 'Import from sheet', 'Lender remittance'];

const css = `
.pc{--bg:#11191b;--panel:#192325;--panel2:#202c2d;--panel3:#263534;--ink:#e6eee9;--muted:#9aaba5;--quiet:#6f827c;--line:#334441;--line2:#2a3837;--accent:#9bd1bf;--accent2:#4c9f90;--amber:#d3ad72;min-height:100vh;background:var(--bg);color:var(--ink);font:12px/1.4 'DM Sans',ui-sans-serif,system-ui,sans-serif;letter-spacing:-.01em;-webkit-font-smoothing:antialiased}
.pc *{box-sizing:border-box}.pc button,.pc input,.pc select,.pc textarea{font:inherit}.pc-shell{display:grid;grid-template-columns:72px 198px minmax(0,1fr);min-height:100vh}
.pc-rail{background:#0d1416;border-right:1px solid #273535;display:flex;flex-direction:column;align-items:center;padding:18px 9px 14px;gap:17px}.pc-glyph{width:36px;height:36px;border:1px solid var(--accent2);color:var(--accent);display:grid;place-items:center;font:700 20px Georgia,serif;position:relative}.pc-glyph:after{content:'';position:absolute;width:5px;height:5px;background:var(--amber);top:-3px;right:-3px}.pc-railmark{width:36px;height:31px;border:1px solid transparent;background:transparent;color:#718680;cursor:pointer;font-size:10px;letter-spacing:.08em}.pc-railmark:hover,.pc-railmark.active{color:var(--accent);border-color:#395c55;background:#172622}.pc-railbottom{margin-top:auto;display:grid;gap:12px;text-align:center;color:#70827d;font-size:10px}.pc-avatar{width:28px;height:28px;background:#2d4c48;color:#cde9dc;display:grid;place-items:center;border-radius:50%;font-weight:700}
.pc-index{background:#151f20;border-right:1px solid var(--line);padding:19px 13px;display:flex;flex-direction:column;min-width:0}.pc-brand{padding:0 5px 18px;border-bottom:1px solid var(--line);margin-bottom:17px}.pc-brand strong{display:block;font-family:Georgia,serif;font-size:16px;font-weight:500;color:#f0f5ee;letter-spacing:.01em}.pc-brand span{display:block;margin-top:4px;color:var(--quiet);font-size:10px;text-transform:uppercase;letter-spacing:.13em}.pc-indexlabel{color:var(--accent);font-size:9px;text-transform:uppercase;letter-spacing:.16em;font-weight:800;margin:0 5px 9px}.pc-nav{display:grid;gap:3px}.pc-nav a{color:#92a49e;text-decoration:none;padding:8px 6px;display:flex;align-items:center;gap:8px;border-left:2px solid transparent;transition:background .15s,color .15s}.pc-nav a:hover{color:var(--ink);background:#202d2d}.pc-nav a.active{color:var(--ink);background:#243532;border-left-color:var(--accent)}.pc-nav i{width:4px;height:4px;border:1px solid #688078;border-radius:50%}.pc-nav a.active i{background:var(--accent);border-color:var(--accent)}.pc-indexfoot{margin-top:auto;border-top:1px solid var(--line);padding-top:13px;display:grid;gap:9px}.pc-indexfoot select{height:29px;background:#202c2d;border:1px solid #3a4b48;color:#dbe6df;padding:0 6px;font-size:10px}.pc-indexfoot button{background:none;border:0;color:#81948d;text-align:left;padding:0;cursor:pointer;font-size:10px}.pc-indexfoot button:hover{color:var(--accent)}
.pc-main{min-width:0;background:linear-gradient(120deg,#182123 0%,#121a1c 65%)}.pc-top{height:66px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;padding:0 26px;background:#151f20}.pc-topline{display:flex;align-items:center;gap:12px}.pc-top h1{font-size:19px;margin:0;font-weight:700;letter-spacing:-.04em}.pc-crumb{font:10px ui-monospace,SFMono-Regular,monospace;color:var(--quiet);letter-spacing:.08em;text-transform:uppercase;border-left:1px solid var(--line);padding-left:12px}.pc-readout{display:flex;align-items:center;gap:17px;color:var(--muted);font-size:10px}.pc-readout span{display:flex;gap:6px;align-items:center}.pc-readout i{width:6px;height:6px;background:var(--accent);border-radius:50%}.pc-readout b{color:var(--ink);font-weight:600}.pc-command{margin-left:18px;border:1px solid #3c514c;background:#1f2d2c;color:#b9d3c8;padding:6px 9px;font:10px ui-monospace,SFMono-Regular,monospace;cursor:pointer}.pc-command:hover{background:#29413b}
.pc-body{padding:19px 25px 34px;max-width:1160px}.pc-workbar{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line);padding-bottom:13px;margin-bottom:15px}.pc-workbar h2{font-size:16px;margin:4px 0 0;letter-spacing:-.035em}.pc-workbar p{margin:0;color:var(--muted);font-size:11px}.pc-code{font:10px ui-monospace,SFMono-Regular,monospace;color:#789088;letter-spacing:.08em}.pc-tabs{display:flex;gap:0;overflow:auto;border:1px solid var(--line);background:#10191a;margin-bottom:16px}.pc-tabs button{border:0;border-right:1px solid var(--line);background:transparent;color:#869a93;padding:8px 10px;white-space:nowrap;font-size:10px;cursor:pointer}.pc-tabs button:hover{color:var(--ink);background:#21302e}.pc-tabs button.on{background:var(--accent);color:#12201d;font-weight:800}
.pc-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(250px,.65fr);gap:14px;align-items:start}.pc-stack{display:grid;gap:12px}.pc-card{background:var(--panel);border:1px solid var(--line);min-width:0}.pc-head{min-height:53px;padding:12px 15px 10px;border-bottom:1px solid var(--line2);display:flex;justify-content:space-between;gap:12px;align-items:start}.pc-head h3{margin:0;font-size:12px;font-weight:750;letter-spacing:.01em}.pc-head p{margin:3px 0 0;color:var(--muted);font-size:10px;line-height:1.35}.pc-head code{color:#718781;font:9px ui-monospace,SFMono-Regular,monospace}.pc-inner{padding:14px 15px}.pc-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.pc-field{display:grid;gap:5px}.pc-field label,.pc-field>span:first-child{font-size:9px;color:#8fa39b;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.pc-field input,.pc-field select,.pc-field textarea{width:100%;height:32px;background:#111a1b;border:1px solid #3a4a47;color:#e1ebe4;padding:0 8px;border-radius:2px;outline:none}.pc-field textarea{height:auto;padding:7px;line-height:1.55;resize:vertical}.pc-field input:focus,.pc-field select:focus,.pc-field textarea:focus{border-color:var(--accent2);box-shadow:0 0 0 2px #387a6d44}.pc-help{color:#71847e;font-size:10px;line-height:1.35}.pc-actions{display:flex;align-items:center;gap:10px;margin-top:13px}.pc-save{height:29px;border:1px solid var(--accent2);background:var(--accent2);color:#071412;padding:0 11px;font-size:10px;font-weight:800;cursor:pointer}.pc-save:hover{background:var(--accent);border-color:var(--accent)}.pc-saved{color:var(--accent);font:10px ui-monospace,SFMono-Regular,monospace}
.pc-toggle{display:grid;grid-template-columns:28px 1fr;gap:9px;align-items:start;padding-bottom:11px}.pc-toggle:last-of-type{padding-bottom:0}.pc-toggle button{width:26px;height:15px;background:#3a4846;border:1px solid #566661;border-radius:10px;padding:0;position:relative;cursor:pointer}.pc-toggle button:after{content:'';position:absolute;width:9px;height:9px;top:2px;left:2px;background:#a1b0ab;border-radius:50%;transition:transform .17s}.pc-toggle button.on{background:#357c6e;border-color:#56a996}.pc-toggle button.on:after{transform:translateX(11px);background:#e4f5eb}.pc-toggle strong{display:block;font-size:11px;line-height:1.2}.pc-toggle p{margin:3px 0 0;color:#80928b;font-size:10px;line-height:1.35}.pc-rule{height:1px;background:var(--line2);margin:3px 0 12px}.pc-notice{border-left:2px solid var(--amber);background:#27271f;color:#b7b09a;padding:9px 10px;font-size:10px;line-height:1.45;margin-top:12px}.pc-notice b{display:block;color:#dbc487;text-transform:uppercase;letter-spacing:.1em;font-size:9px;margin-bottom:3px}.pc-sidecard{background:#172122;border:1px solid var(--line);padding:13px}.pc-sidecard h4{margin:0 0 11px;color:var(--accent);font-size:9px;text-transform:uppercase;letter-spacing:.14em}.pc-stat{display:flex;justify-content:space-between;border-bottom:1px solid var(--line2);padding:8px 0;color:#8ca099;font-size:10px}.pc-stat:last-child{border-bottom:0}.pc-stat strong{color:var(--ink);font:11px ui-monospace,SFMono-Regular,monospace}.pc-event{display:grid;grid-template-columns:7px 1fr auto;gap:8px;padding:8px 0;border-bottom:1px solid var(--line2)}.pc-event:last-child{border:0}.pc-event i{width:5px;height:5px;background:var(--accent2);margin-top:4px}.pc-event b{display:block;font-size:10px;font-weight:600}.pc-event span,.pc-event time{color:#72857e;font-size:9px}.pc-event time{font-family:ui-monospace,SFMono-Regular,monospace}.pc-wide{grid-column:1/-1}
@media(max-width:980px){.pc-shell{grid-template-columns:62px 175px minmax(0,1fr)}.pc-layout{grid-template-columns:1fr}.pc-sidecol{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pc-sidecard{min-width:0}}
@media(max-width:720px){.pc-shell{display:block}.pc-rail{display:none}.pc-index{padding:13px;min-height:auto}.pc-brand{margin-bottom:10px;padding-bottom:12px}.pc-nav{display:flex;overflow:auto}.pc-nav a{white-space:nowrap}.pc-indexlabel,.pc-indexfoot{display:none}.pc-top{height:63px;padding:0 14px}.pc-readout{display:none}.pc-body{padding:14px 12px}.pc-workbar{display:block}.pc-code{display:block;margin-top:8px}.pc-form{grid-template-columns:1fr}.pc-wide{grid-column:auto}.pc-sidecol{display:block}.pc-sidecard{margin-top:12px}}
`;

function Toggle({ title, hint, initial = true }: { title: string; hint: string; initial?: boolean }) {
  const [on, setOn] = useState(initial);
  return <div className="pc-toggle"><button type="button" className={on ? 'on' : ''} aria-label={`${title}: ${on ? 'on' : 'off'}`} aria-pressed={on} onClick={() => setOn(!on)} /><div><strong>{title}</strong><p>{hint}</p></div></div>;
}

function SaveButton({ children }: { children: ReactNode }) {
  const [saved, setSaved] = useState(false);
  return <div className="pc-actions"><button type="button" className="pc-save" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }}>{children}</button>{saved && <span className="pc-saved" role="status">COMMITTED · just now</span>}</div>;
}

function Card({ title, note, code, className = '', children }: { title: string; note: string; code: string; className?: string; children: ReactNode }) {
  return <section className={`pc-card ${className}`}><div className="pc-head"><div><h3>{title}</h3><p>{note}</p></div><code>{code}</code></div><div className="pc-inner">{children}</div></section>;
}

export function PrecisionConsole() {
  const [tab, setTab] = useState('Portal');
  const [destination, setDestination] = useState('Settings');
  const [names, setNames] = useState({ company: 'Greystone Merchant Partners', portal: 'Commission portal', email: 'ops@greystone.com' });
  const [lists, setLists] = useState({ frequencies: 'Weekly\nBi-weekly\nMonthly', statuses: 'Performing\nProspecting\nRefi Ready' });
  return <div className="pc"><style>{css}</style><div className="pc-shell">
    <aside className="pc-rail" aria-label="Workspace shortcuts"><div className="pc-glyph">G</div><button className="pc-railmark active" type="button" aria-label="Settings workspace">CFG</button><button className="pc-railmark" type="button" aria-label="Audit log">LOG</button><button className="pc-railmark" type="button" aria-label="Command search">⌘K</button><div className="pc-railbottom"><div className="pc-avatar">L</div><span>v2.4</span></div></aside>
    <aside className="pc-index"><div className="pc-brand"><strong>Greystone</strong><span>Commission operations</span></div><div className="pc-indexlabel">Workspace index</div><nav className="pc-nav" aria-label="Primary navigation">{destinations.map(item => <a href={`#${item.toLowerCase().replaceAll(' ', '-')}`} className={destination === item ? 'active' : ''} onClick={() => setDestination(item)} key={item}><i />{item}</a>)}</nav><div className="pc-indexfoot"><select defaultValue="admin" aria-label="View as"><option value="admin">Admin — master view</option></select><button type="button">Change password</button><button type="button">Two-factor sign-in</button><button type="button">Sign out</button></div></aside>
    <main className="pc-main"><header className="pc-top"><div className="pc-topline"><h1>Settings</h1><span className="pc-crumb">/ admin / controls / {tab.toLowerCase()}</span></div><div className="pc-readout"><span><i />SYSTEM NOMINAL</span><span>LAST COMMIT <b>02 MIN AGO</b></span><button type="button" className="pc-command">COMMAND ⌘K</button></div></header>
      <div className="pc-body"><div className="pc-tabs" role="tablist" aria-label="Settings destinations">{settingsTabs.map(item => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'on' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>
        <div className="pc-workbar"><div><div className="pc-code">ACTIVE SCOPE / GLOBAL / PORTAL.00</div><h2>{tab} control surface</h2><p>Exact changes propagate to every rep, admin, and automated message.</p></div><span className="pc-code">CONFIG REVISION 2.4.18</span></div>
        <div className="pc-layout"><div className="pc-stack">
          <Card title="Portal identity" note="Names shown in the sidebar, sign-in screen, emails and authenticator apps." code="PORTAL.01"><div className="pc-form"><div className="pc-field"><label>Company</label><input value={names.company} onChange={e => setNames({ ...names, company: e.target.value })} /></div><div className="pc-field"><label>Portal name</label><input value={names.portal} onChange={e => setNames({ ...names, portal: e.target.value })} /></div><div className="pc-field"><label>Support email</label><input value={names.email} onChange={e => setNames({ ...names, email: e.target.value })} /><span className="pc-help">Shown to reps when something needs a human.</span></div></div><SaveButton>Commit names</SaveButton></Card>
          <Card title="Automatic emails" note="Each event is logged in the Audit log as mail.sent." code="PORTAL.02"><Toggle title="Statements when a run is approved" hint="Every rep with lines in the run gets their summary and a link to Pay history." /><Toggle title="Clawback notices" hint="Each rep with a slice hears the amount and that it nets against their next payout." /><Toggle title="Rep questions to admins" hint="Admins receive the note when a rep asks about a deal from their drawer." /><Toggle title="Daily renewal digest" hint="Refi-ready and Prospecting deals, to every admin, once a day." /><div className="pc-rule" /><div className="pc-form"><div className="pc-field"><label>Digest goes out at</label><select defaultValue="8"><option value="8">08 your time · 13:00 UTC</option></select></div><div className="pc-field"><label>Playbooks run daily at</label><select defaultValue="7"><option value="7">07 your time · 12:00 UTC</option></select><span className="pc-help">Playbooks fire once a day after this hour; rep emails roll into one message.</span></div></div><SaveButton>Commit email controls</SaveButton><div className="pc-notice"><b>Protected secret boundary</b>The sending address and provider key live in host Secrets (MAIL_PROVIDER, MAIL_API_KEY, MAIL_FROM). They never change from here.</div></Card>
          <Card title="Permissions" note="What reps may do from their portal." code="PORTAL.03"><Toggle title="Reps can email merchants from a deal" hint="Off hides the button for everyone. Individual reps can still be blocked under Reps › Merchant email." /><Toggle title="Reps can fill in merchant details on their deals" hint="Contact name, email and phone — never the business name or money. Changes are audited." /><SaveButton>Commit permissions</SaveButton></Card>
          <Card title="Security" note="Passwords, two-factor controls and session duration." code="PORTAL.04"><Toggle title="Require two-factor for admins" hint="Admins without an authenticator are held at setup until they enroll." /><div className="pc-form"><div className="pc-field"><label>Sign out after inactivity</label><select defaultValue="4"><option value="4">4 hours</option></select><span className="pc-help">Everyone, admins included. The server refuses the old session too.</span></div><div className="pc-field"><label>Remember device after two-factor</label><select defaultValue="14"><option value="14">14 days</option></select><span className="pc-help">Password remains required; the code is skipped on a remembered browser.</span></div></div><SaveButton>Commit security</SaveButton></Card>
          <Card title="Dropdown lists" note="One per line · commission statuses are fixed because they drive collection." code="PORTAL.05"><div className="pc-form"><div className="pc-field"><label>Payment frequencies</label><textarea rows={4} value={lists.frequencies} onChange={e => setLists({ ...lists, frequencies: e.target.value })} /></div><div className="pc-field"><label>Deal statuses</label><textarea rows={4} value={lists.statuses} onChange={e => setLists({ ...lists, statuses: e.target.value })} /><span className="pc-help">Keep Performing, Prospecting and Refi Ready — the portal sets those itself.</span></div></div><SaveButton>Commit lists</SaveButton></Card>
        </div><aside className="pc-sidecol"><div className="pc-sidecard"><h4>Control telemetry</h4><div className="pc-stat"><span>Configuration health</span><strong>READY</strong></div><div className="pc-stat"><span>Active admins</span><strong>04</strong></div><div className="pc-stat"><span>2FA coverage</span><strong>75%</strong></div><div className="pc-stat"><span>Automations</span><strong>04 / 04</strong></div><div className="pc-stat"><span>Audit events</span><strong>12 / 30D</strong></div></div><div className="pc-sidecard"><h4>Recent commits</h4><div className="pc-event"><i /><div><b>Portal name updated</b><span>Identity controls</span></div><time>02m</time></div><div className="pc-event"><i /><div><b>Policy review completed</b><span>Security controls</span></div><time>01d</time></div><div className="pc-event"><i /><div><b>Renewal digest sent</b><span>mail.sent · 08:00</span></div><time>01d</time></div></div><div className="pc-sidecard"><h4>Operator note</h4><p style={{ margin: 0, color: '#91a39c', fontSize: 10, lineHeight: 1.55 }}>Portal controls are global. Use the section index above to switch configuration domains without leaving the console.</p></div></aside></div>
      </div>
    </main>
  </div></div>;
}